[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[selection]
save_to_clipboard = true

# Colors (Gruvbox dark)
# Default colors
# [colors.primary]
# # hard contrast background = = '#1d2021'
# # soft contrast background = = '#32302f'
# # background = '#181818'
# # background = '#000000'
# background = '#0f0f0f'
#
# # Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'
#
# # Bright colors
# [colors.bright]
# black   = '#928374'
# red     = '#fb4934'
# green   = '#b8bb26'
# yellow  = '#fabd2f'
# blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
# white   = '#ebdbb2'
